#!/bin/bash

if [ -e $( dirname "${0}" )/nsenter ]; then
    # with boot2docker, nsenter is not in the PATH but it is in the same folder
    NSENTER=$( dirname "${0}" )/nsenter
else
    NSENTER=nsenter
fi

if [ -z "$1" ]; then
    echo "Usage: `basename "$0"` CONTAINER [COMMAND [ARG]...]"
    echo ""
    echo "Enters the Docker CONTAINER and executes the specified COMMAND."
    echo "If COMMAND is not specified, runs an interactive shell in CONTAINER."
else
    PID=$( docker inspect --format "{{.State.Pid}}" "${1}" )
    [ -z "${PID}" ] && exit 1
    shift
    COMMAND="${@}"

    if [ "$( id -u )" -ne "0" ]; then
        echo "ERROR: must run as root" >&2
        exit 1
    fi
    
    # Get environment variables from the container's root process
    ENV=$( cat /proc/${PID}/environ | xargs -0 )
    
    # If no command is given, default to `su` which executes the default login shell
    # Otherwise, execute the given command
    [ -z "${COMMAND}" ] && COMMAND="su -m root"
    
    # Prepare nsenter flags
    OPTS="--target ${PID} --mount --uts --ipc --net --pid --"

    # Use env to clear all host environment variables and set then anew
    # carry along TERM, so pagers, etc, will work
    "${NSENTER}" ${OPTS} env -i ${ENV} TERM=${TERM} ${COMMAND}
fi
